export type DailyStoicQuote = {
  month: number;
  day: number;
  title: string;
  quote: string;
  author: string;
};

export const STOIC_QUOTES: DailyStoicQuote[] = [
  {
    month: 1,
    day: 1,
    title: "CONTROLE E ESCOLHA",
    quote:
      "A principal tarefa na vida é distinguir o que depende de nós e o que não depende.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 2,
    title: "EDUCAÇÃO É LIBERDADE",
    quote:
      "Somente os educados são livres, pois aprendem a governar a si mesmos.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 3,
    title: "DIGA NÃO AO QUE DISPERSA",
    quote:
      "Muito do que consome nossa vida não merece nossa atenção nem nosso tempo.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 4,
    title: "AS GRANDES TRÊS",
    quote:
      "Julga com clareza, age com justiça e aceita com dignidade o que não controlas.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 5,
    title: "INTENÇÃO CLARA",
    quote: "Quem não sabe para onde vai se perde facilmente no ruído do mundo.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 6,
    title: "ONDE, QUEM, O QUÊ E POR QUÊ",
    quote: "Quem não sabe por que está aqui também não sabe quem é.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 7,
    title: "TREINE A MENTE",
    quote:
      "O trabalho da mente é julgar com clareza, escolher bem e não se enganar.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 8,
    title: "PERCEBA SEUS VÍCIOS",
    quote:
      "Aquilo sem o qual você acha que não consegue viver já começou a governar você.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 9,
    title: "O QUE DEPENDE DE VOCÊ",
    quote: "Controlamos nossas escolhas, não os acontecimentos externos.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 10,
    title: "SEJA ESTÁVEL",
    quote: "A estabilidade nasce de um julgamento correto sobre as coisas.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 11,
    title: "NÃO ENTRE EM AGITAÇÃO",
    quote:
      "Quem busca controlar o que é dos outros vive com medo e perturbação.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 12,
    title: "A SERENIDADE POSSÍVEL",
    quote:
      "Há um caminho para a serenidade: abandonar o que não está na sua escolha.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 13,
    title: "CÍRCULO DE CONTROLE",
    quote: "Sua mente é sua principal responsabilidade.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 14,
    title: "ROMPA AS AMARRAS",
    quote: "Você tem em si algo mais forte que aquilo que tenta dominá-lo.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 15,
    title: "MANTENHA O RUMO",
    quote:
      "A paz vem de seguir o caminho certo sem se perder na opinião comum.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 16,
    title: "NADA POR HÁBITO",
    quote: "Não faça automaticamente o que exige consciência.",
    author: "Musônio Rufo",
  },
  {
    month: 1,
    day: 17,
    title: "RECOMECE O TRABALHO",
    quote: "Deixe o passado para trás. O importante é começar agora.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 18,
    title: "VEJA COM MAIS PROFUNDIDADE",
    quote: "Há beleza e ordem para quem aprende a olhar com atenção.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 19,
    title: "ONDE VOCÊ ESTÁ, LÁ ESTÁ SUA ESCOLHA",
    quote: "Em qualquer lugar, sua liberdade moral ainda pode ser preservada.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 20,
    title: "REACENDA SEUS PENSAMENTOS",
    quote: "É possível começar de novo ao ver as coisas de maneira diferente.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 21,
    title: "RITUAL MATINAL",
    quote:
      "Pergunte a si mesmo pela manhã o que precisa corrigir para viver melhor hoje.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 22,
    title: "REVISE O DIA",
    quote: "Examine cada dia com honestidade e você não viverá no automático.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 23,
    title: "A VERDADE SOBRE O DINHEIRO",
    quote: "Ter mais não cura uma alma confusa.",
    author: "Sêneca",
  },
  {
    month: 1,
    day: 24,
    title: "BUSQUE COMPREENDER MELHOR",
    quote: "Não se satisfaça com uma compreensão superficial.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 25,
    title: "O PRÊMIO CERTO",
    quote: "Respeite sua própria mente mais do que aquilo que o mundo aplaude.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 26,
    title: "TENHA UM MANTRA",
    quote: "Você tem dentro de si o poder de ver as coisas como elas são.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 27,
    title: "TRÊS ÁREAS DE TREINO",
    quote: "Treine seus desejos, suas ações e seus julgamentos.",
    author: "Epicteto",
  },
  {
    month: 1,
    day: 28,
    title: "OBSERVE OS SÁBIOS",
    quote: "Veja com atenção o que as pessoas sábias buscam e o que evitam.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 29,
    title: "MANTENHA A SIMPLICIDADE",
    quote: "Faça cada tarefa com simplicidade, dignidade e presença.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 30,
    title: "PARE DE EXPLICAR, PRATIQUE",
    quote: "Não explique demais como viver bem. Viva bem.",
    author: "Marco Aurélio",
  },
  {
    month: 1,
    day: 31,
    title: "FILOSOFIA É PRÁTICA",
    quote: "A filosofia não serve para parecer sábio, mas para viver melhor.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 1,
    title: "PAIXÕES SOB EXAME",
    quote: "Não entregue sua mente ao primeiro impulso que surgir.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 2,
    title: "A RAIVA ENCURTA A VISÃO",
    quote: "A raiva nos faz ver menos do que a realidade exige.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 3,
    title: "ESPERE ANTES DE REAGIR",
    quote: "Entre o acontecimento e a resposta existe um espaço de escolha.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 4,
    title: "NÃO SE TORNE ESCRAVO DO HUMOR",
    quote: "Quem depende do próprio humor para agir entrega a vida ao acaso.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 5,
    title: "EMOÇÃO NÃO É COMANDO",
    quote: "Sentir não obriga; escolher continua sendo seu dever.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 6,
    title: "CALMA É FORÇA",
    quote: "A mente tranquila enxerga melhor e decide melhor.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 7,
    title: "CUIDADO COM O EXAGERO",
    quote:
      "Muitas perturbações nascem quando ampliamos demais o que aconteceu.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 8,
    title: "NOMEIE O QUE SENTE",
    quote:
      "Aquilo que você nomeia com clareza perde parte do poder sobre você.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 9,
    title: "NÃO ALIMENTE O FOGO",
    quote: "Uma paixão cresce quando é repetida em pensamento.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 10,
    title: "A OFENSA PASSA PELO JULGAMENTO",
    quote: "Não são as coisas que nos ferem, mas o juízo que fazemos delas.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 11,
    title: "A PRESSA ERRA",
    quote:
      "Responder imediatamente nem sempre é sinal de força; muitas vezes é só impulso.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 12,
    title: "GUARDE SEU CENTRO",
    quote: "Quando o mundo se agita, volte para o governo da sua mente.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 13,
    title: "A PAIXÃO PROMETE DEMAIS",
    quote:
      "O que parece urgente sob emoção costuma parecer menor quando a mente clareia.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 14,
    title: "NÃO SE CONFUNDA COM O IMPULSO",
    quote:
      "Você não é a onda que passa; você é quem decide o que fazer com ela.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 15,
    title: "O TREINO É DIÁRIO",
    quote: "A serenidade não aparece pronta; ela é praticada.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 16,
    title: "A MENTE SE TINGE",
    quote: "A alma toma a cor dos pensamentos que você cultiva.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 17,
    title: "EVITE O DRAMA",
    quote: "Nem toda dor precisa se transformar em espetáculo interior.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 18,
    title: "VOLTE AO FATO",
    quote: "Separe o fato da história que você contou sobre ele.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 19,
    title: "A FORÇA DE PAUSAR",
    quote: "Pausar antes de reagir já é uma forma de liberdade.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 20,
    title: "NÃO EMPRESTE PODER",
    quote: "Quando tudo o afeta, tudo começa a comandá-lo.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 21,
    title: "A IRA COBRA CARO",
    quote: "A raiva costuma punir primeiro quem a abriga.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 22,
    title: "DOMÍNIO DE SI",
    quote: "Mais nobre que vencer alguém é governar a si mesmo.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 23,
    title: "NÃO REAJA A TUDO",
    quote: "Nem todo estímulo merece resposta; às vezes basta deixá-lo passar.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 24,
    title: "CLAREZA SOBRE O DESEJO",
    quote: "Desejos desordenados transformam abundância em carência.",
    author: "Sêneca",
  },
  {
    month: 2,
    day: 25,
    title: "MENOS AGITAÇÃO, MAIS VERDADE",
    quote: "A verdade aparece melhor quando a mente deixa de se debater.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 26,
    title: "TOLERE O DESCONFORTO",
    quote: "Nem todo desconforto é ameaça; muitas vezes é só parte do treino.",
    author: "Epicteto",
  },
  {
    month: 2,
    day: 27,
    title: "RECOLHA-SE",
    quote: "Você pode voltar a si mesmo sempre que o mundo tentar arrastá-lo.",
    author: "Marco Aurélio",
  },
  {
    month: 2,
    day: 28,
    title: "PAIXÃO SOB GOVERNO",
    quote: "A liberdade começa quando a emoção deixa de mandar em tudo.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 1,
    title: "CONSCIÊNCIA DE SI",
    quote:
      "Examine seus pensamentos, porque deles nasce a direção da sua vida.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 2,
    title: "OLHE PARA DENTRO",
    quote:
      "Antes de corrigir o mundo, observe o que em você ainda precisa de ordem.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 3,
    title: "SEJA TESTEMUNHA DE SI",
    quote:
      "A mente pode aprender a se observar sem se confundir com cada impulso.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 4,
    title: "NÃO VIVA NO AUTOMÁTICO",
    quote: "Quem não se examina repete a vida em vez de vivê-la com presença.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 5,
    title: "A CLAREZA COMEÇA NO JULGAMENTO",
    quote:
      "Você se perde menos quando aprende a ver corretamente o que acontece.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 6,
    title: "O HÁBITO DE REFLETIR",
    quote: "Revisar o dia é uma forma de não desperdiçar a própria vida.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 7,
    title: "VEJA O QUE REPETE",
    quote:
      "Os padrões se enfraquecem quando finalmente são vistos com honestidade.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 8,
    title: "CONHECE-TE NO COTIDIANO",
    quote:
      "Você se revela nas pequenas escolhas, não só nos grandes discursos.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 9,
    title: "PARE E OBSERVE",
    quote: "Nem toda urgência merece movimento; algumas pedem observação.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 10,
    title: "HONESTIDADE SEM CRUELDADE",
    quote: "Olhar para si com verdade não exige violência, exige coragem.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 11,
    title: "RECONHEÇA O EXAGERO",
    quote:
      "Muitas vezes não sofremos só pelo fato, mas pelo excesso que colocamos sobre ele.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 12,
    title: "O CENTRO ESTÁ EM VOCÊ",
    quote: "Volte para dentro: ali ainda existe um lugar de governo e lucidez.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 13,
    title: "VIGIE A PRIMEIRA IMPRESSÃO",
    quote:
      "A primeira impressão chega rápido; o julgamento correto precisa ser escolhido.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 14,
    title: "NÃO CONFUNDA SENTIR COM SABER",
    quote: "Sentir algo intensamente não o torna verdadeiro.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 15,
    title: "ORDEM INTERIOR",
    quote:
      "A vida externa se organiza melhor quando a mente deixa de ser uma arena.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 16,
    title: "SEJA ALUNO DE SI",
    quote:
      "Todos os dias há algo em você para observar, corrigir e fortalecer.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 17,
    title: "ESCUTE O QUE O DIA MOSTROU",
    quote:
      "Cada dia revela algo sobre seu caráter para quem decide prestar atenção.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 18,
    title: "NÃO FUJA DO ESPELHO",
    quote: "O autoconhecimento dói menos do que viver fugindo de si mesmo.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 19,
    title: "TREINE A ATENÇÃO",
    quote: "Uma mente atenta sofre menos com o próprio descuido.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 20,
    title: "PENSE MELHOR",
    quote: "Pensamentos descuidados produzem dias descuidados.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 21,
    title: "O QUE ESTÁ TE GUIANDO?",
    quote:
      "Pergunte sempre: estou sendo guiado pela razão ou apenas arrastado?",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 22,
    title: "REVISÃO HONESTA",
    quote: "A revisão do dia não é punição; é ajuste de rota.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 23,
    title: "MENOS ILUSÃO, MAIS REALIDADE",
    quote:
      "Você se fortalece quando prefere a verdade ao conforto da fantasia.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 24,
    title: "SEJA CLARO CONSIGO",
    quote: "Não esconda de si aquilo que já ficou evidente.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 25,
    title: "ATENÇÃO ÀS ORIGENS",
    quote:
      "Observe de onde nasce cada ação: de clareza, medo, vaidade ou dever?",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 26,
    title: "A MENTE PODE SER REEDUCADA",
    quote:
      "Você não é obrigado a seguir para sempre a primeira forma como aprendeu a reagir.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 27,
    title: "CONSCIÊNCIA É PRÁTICA",
    quote: "Não basta querer lucidez; é preciso praticá-la no cotidiano.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 28,
    title: "UM DIA BEM EXAMINADO",
    quote: "O dia bem examinado se torna matéria de crescimento.",
    author: "Sêneca",
  },
  {
    month: 3,
    day: 29,
    title: "RECOLHA O APRENDIZADO",
    quote:
      "Nada vivido precisa ser desperdiçado se você recolhe o aprendizado.",
    author: "Marco Aurélio",
  },
  {
    month: 3,
    day: 30,
    title: "A VERDADE LIBERTA",
    quote:
      "A verdade interior pode ser incômoda, mas é melhor do que viver enganado.",
    author: "Epicteto",
  },
  {
    month: 3,
    day: 31,
    title: "A CONSCIÊNCIA ENDIREITA O CAMINHO",
    quote: "Quem se observa com constância erra menos por repetição cega.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 1,
    title: "PENSAMENTO IMPARCIAL",
    quote:
      "Veja as coisas como são, não apenas como você teme ou deseja que sejam.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 2,
    title: "SEM DRAMA DESNECESSÁRIO",
    quote: "Retire o exagero e metade do sofrimento já se desfaz.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 3,
    title: "FATO E INTERPRETAÇÃO",
    quote:
      "Uma coisa é o acontecimento; outra, a opinião que você formou sobre ele.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 4,
    title: "JULGUE COM CALMA",
    quote: "A mente precipitada confunde velocidade com verdade.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 5,
    title: "NÃO ACREDITE EM TUDO QUE PENSA",
    quote: "Toda impressão deve ser examinada antes de virar crença.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 6,
    title: "CLAREZA SOBRE A REALIDADE",
    quote:
      "A realidade não precisa ser embelezada nem piorada; precisa ser vista.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 7,
    title: "O PESO DA OPINIÃO",
    quote: "Muitas dores nascem quando tratamos opinião como se fosse fato.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 8,
    title: "NÃO SEJA ARRASTADO",
    quote: "Quem não examina a própria impressão é levado por ela.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 9,
    title: "SEJA JUSTO ATÉ CONSIGO",
    quote: "O pensamento imparcial também exige parar de distorcer a si mesmo.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 10,
    title: "MENOS RUÍDO, MAIS VISÃO",
    quote: "O ruído emocional embaralha aquilo que a razão poderia ordenar.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 11,
    title: "RECUSE A DISTORÇÃO",
    quote: "Nem tudo que parece insulto é, de fato, uma ofensa real.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 12,
    title: "VEJA O TAMANHO CERTO",
    quote: "Parte da sabedoria é devolver às coisas sua proporção exata.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 13,
    title: "A IMPARCIALIDADE PROTEGE",
    quote:
      "Quando você julga melhor, sofre menos com o que inventou sobre o fato.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 14,
    title: "NOME CORRETO, PESO CORRETO",
    quote:
      "Chame cada coisa pelo nome certo e ela perderá muito do poder teatral.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 15,
    title: "SEM ILUSÃO VOLUNTÁRIA",
    quote: "Não escolha a cegueira só porque a verdade exige maturidade.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 16,
    title: "A PRIMEIRA VERSÃO NÃO É A FINAL",
    quote: "A primeira leitura de um fato raramente é a mais sábia.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 17,
    title: "VOLTE AO QUE IMPORTA",
    quote: "O pensamento correto corta o excesso e retorna ao essencial.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 18,
    title: "SEPARAR AJUDA A VER",
    quote: "Separar aparência de substância já é metade da lucidez.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 19,
    title: "OPINIÃO COM DISCIPLINA",
    quote: "Nem toda interpretação merece permanecer em sua mente.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 20,
    title: "VEJA SEM VAIDADE",
    quote: "A vaidade também distorce a visão do real.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 21,
    title: "A VERDADE NÃO PRECISA DE ENFEITE",
    quote: "Ver claramente exige menos fantasia e mais sobriedade.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 22,
    title: "NÃO SEJA ADVOGADO DO ENGANO",
    quote:
      "Quanto mais você defende uma impressão ruim, mais se afasta da paz.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 23,
    title: "A CALMA TORNA A VISÃO MAIS JUSTA",
    quote: "A mente calma não é ingênua; ela apenas vê melhor.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 24,
    title: "SEJA EXATO",
    quote: "A precisão do pensamento protege contra a confusão desnecessária.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 25,
    title: "RECUSE A NARRATIVA EXCESSIVA",
    quote: "Nem todo fato precisa virar história dramática.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 26,
    title: "A IMPARCIALIDADE É UM TREINO",
    quote: "Pensar com justiça não é um dom; é disciplina repetida.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 27,
    title: "VER SEM SE ILUDIR",
    quote: "A lucidez pode doer no começo, mas poupa sofrimento adiante.",
    author: "Epicteto",
  },
  {
    month: 4,
    day: 28,
    title: "MENOS OPINIÃO, MAIS OBSERVAÇÃO",
    quote: "Observe mais antes de concluir.",
    author: "Marco Aurélio",
  },
  {
    month: 4,
    day: 29,
    title: "A RAZÃO TEM SEU TEMPO",
    quote: "O julgamento maduro raramente nasce da pressa.",
    author: "Sêneca",
  },
  {
    month: 4,
    day: 30,
    title: "A VISÃO CORRETA ALIVIA",
    quote: "Quando o pensamento se endireita, muito peso desnecessário cai.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 1,
    title: "AÇÃO CORRETA",
    quote:
      "Não perca mais tempo discutindo o que um homem bom deve ser. Seja um.",
    author: "Marco Aurélio",
  },

  {
    month: 5,
    day: 2,
    title: "FAÇA O QUE CABE",
    quote: "O dever mais próximo costuma ser o mais importante.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 3,
    title: "AJA, NÃO SÓ PENSE",
    quote:
      "A filosofia se prova no modo como você vive, não no que você explica.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 4,
    title: "AÇÃO COM JUSTIÇA",
    quote: "Que cada ato teu seja digno do ser humano que queres te tornar.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 5,
    title: "NÃO ADIE O BEM",
    quote: "Aquilo que é correto não deve esperar por um humor melhor.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 6,
    title: "COMECE PELO PRÓXIMO PASSO",
    quote: "Grandes caminhos se sustentam em ações pequenas e corretas.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 7,
    title: "AÇÃO SEM EXIBIÇÃO",
    quote: "Faça o certo sem precisar transformar isso em vitrine.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 8,
    title: "MENOS DESCULPA, MAIS CONDUTA",
    quote: "O caráter amadurece quando a ação substitui a justificativa.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 9,
    title: "O BEM EXIGE MOVIMENTO",
    quote: "Intenção sem ação ainda não mudou nada no mundo.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 10,
    title: "FAÇA SUA PARTE",
    quote: "Mesmo que o mundo não colabore, sua parte continua sendo sua.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 11,
    title: "AÇÃO LIMPA",
    quote: "Aja sem malícia, sem preguiça e sem encenação.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 12,
    title: "O CERTO É PRÁTICO",
    quote: "O bem não é uma ideia bonita; é um modo de agir.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 13,
    title: "NÃO COMPLIQUE O DEVER",
    quote:
      "Frequentemente sabemos o que precisa ser feito; o difícil é parar de fugir.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 14,
    title: "AJA COM PRESENÇA",
    quote: "A tarefa de agora merece sua atenção inteira.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 15,
    title: "CONSTÂNCIA",
    quote: "Ação correta repetida constrói um caráter confiável.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 16,
    title: "SEM AUTOENGANO",
    quote:
      "Não diga que valoriza a virtude se sua prática continua apontando para outro lado.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 17,
    title: "O BEM EM MOVIMENTO",
    quote: "Toda vez que você age com justiça, a filosofia sai do papel.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 18,
    title: "FAÇA AGORA O QUE É BOM",
    quote:
      "O bem vivido no presente vale mais que grandes intenções para depois.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 19,
    title: "NÃO DEPENDA DE APLAUSO",
    quote: "Uma boa ação não precisa de plateia para continuar sendo boa.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 20,
    title: "SERVE AO BEM COMUM",
    quote:
      "A ação correta também pergunta: isso ajuda só a mim ou também ao todo?",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 21,
    title: "A INÉRCIA ENFRAQUECE",
    quote: "Quanto mais você adia o correto, mais o incorreto ganha espaço.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 22,
    title: "DISCIPLINA É AÇÃO",
    quote: "Disciplina não é falar de ordem; é agir em ordem.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 23,
    title: "SEJA ÚTIL",
    quote:
      "O ser humano foi feito para cooperar, contribuir e agir com propósito.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 24,
    title: "NÃO PARE NO DISCURSO",
    quote: "A sabedoria que não vira conduta ainda não amadureceu.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 25,
    title: "AÇÃO SEM AMARGURA",
    quote:
      "Faça o que deve ser feito sem acrescentar reclamação desnecessária.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 26,
    title: "DÊ O PASSO CERTO",
    quote:
      "Nem sempre é possível fazer tudo, mas quase sempre é possível fazer a próxima coisa certa.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 27,
    title: "AJA COMO QUEM SABE O VALOR DO TEMPO",
    quote: "A vida se encurta quando o essencial é adiado sem necessidade.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 28,
    title: "COERÊNCIA",
    quote:
      "Ação correta é o encontro entre o que você diz valorizar e o que realmente pratica.",
    author: "Epicteto",
  },
  {
    month: 5,
    day: 29,
    title: "FAÇA O BEM SIMPLES",
    quote:
      "Nem sempre a virtude é grandiosa; muitas vezes ela é só o correto feito hoje.",
    author: "Marco Aurélio",
  },
  {
    month: 5,
    day: 30,
    title: "NÃO VIVA EM ENSAIO",
    quote:
      "A vida real não começa depois; ela já está acontecendo nas suas ações de agora.",
    author: "Sêneca",
  },
  {
    month: 5,
    day: 31,
    title: "SEJA A RESPOSTA",
    quote: "Quando o bem precisa acontecer, torne-se você mesmo a resposta.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 1,
    title: "SOLUÇÃO DE PROBLEMAS",
    quote: "Não se perturbe pelo problema antes de olhar com clareza para ele.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 2,
    title: "O OBSTÁCULO EXIGE MÉTODO",
    quote: "Dificuldades não pedem drama, pedem ordem interior e ação correta.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 3,
    title: "DIVIDA O PESO",
    quote: "O que parece impossível inteiro muitas vezes se resolve em partes.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 4,
    title: "VOLTE AO ESSENCIAL",
    quote:
      "Quando tudo parecer confuso, volte ao ponto principal e comece dali.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 5,
    title: "NÃO ANTECIPE O SOFRIMENTO",
    quote:
      "Grande parte do peso vem de lutar com problemas que ainda não chegaram.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 6,
    title: "RESPOSTA EM VEZ DE RECLAMAÇÃO",
    quote:
      "O problema já existe; a questão agora é quem você será diante dele.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 7,
    title: "UMA COISA DE CADA VEZ",
    quote:
      "A mente resolve melhor quando para de tentar carregar tudo ao mesmo tempo.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 8,
    title: "A DIFICULDADE ENSINA",
    quote:
      "Todo obstáculo contém também uma instrução para quem observa com calma.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 9,
    title: "NÃO FAÇA DOER DUAS VEZES",
    quote:
      "Uma vez é o fato; a segunda vez é o excesso criado pelo pensamento.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 10,
    title: "PERGUNTA ÚTIL",
    quote:
      "Em vez de 'por que isso aconteceu?', tente 'o que pode ser feito agora?'",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 11,
    title: "SEJA PRAGMÁTICO",
    quote:
      "Problemas cedem mais à lucidez prática do que à agitação emocional.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 12,
    title: "PARE DE AUMENTAR O PROBLEMA",
    quote: "Não acrescente interpretação catastrófica ao que já é difícil.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 13,
    title: "A CALMA AJUDA A PENSAR",
    quote:
      "A mente ordenada enxerga caminhos onde a mente aflita só vê bloqueio.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 14,
    title: "O QUE DEPENDE DE VOCÊ AGORA",
    quote: "Mesmo no caos, ainda existe alguma parte sob sua responsabilidade.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 15,
    title: "PEQUENAS SOLUÇÕES",
    quote:
      "Resolver um problema grande quase sempre começa com uma solução pequena.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 16,
    title: "AJA SOBRE O REAL",
    quote:
      "Não lute contra fantasmas mentais quando o problema real já pede atenção.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 17,
    title: "NÃO PARALISE",
    quote:
      "Melhor um passo lúcido do que a imobilidade causada pelo excesso de medo.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 18,
    title: "ORDEM ANTES DE PRESSA",
    quote: "A pressa costuma multiplicar o erro que a ordem poderia evitar.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 19,
    title: "TOLERE A COMPLEXIDADE",
    quote:
      "Nem todo problema se resolve rápido; alguns exigem constância serena.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 20,
    title: "O DESCONFORTO NÃO É DERROTA",
    quote:
      "Estar desconfortável enquanto resolve algo não significa que está falhando.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 21,
    title: "SEJA ÚTIL DIANTE DO IMPASSE",
    quote: "Quando não puder resolver tudo, pelo menos impeça que piore.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 22,
    title: "ACEITE O QUE O PROBLEMA EXIGE",
    quote:
      "Alguns problemas pedem coragem; outros, paciência; outros, renúncia.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 23,
    title: "REORGANIZE O PENSAMENTO",
    quote:
      "Às vezes a saída começa quando você reorganiza a forma de ver a situação.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 24,
    title: "MENOS QUEIXA, MAIS TRABALHO",
    quote: "Queixa sem ação é só desgaste a mais.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 25,
    title: "O PROBLEMA NÃO É SUA IDENTIDADE",
    quote:
      "Enfrentar uma dificuldade não significa se tornar a própria dificuldade.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 26,
    title: "CORAGEM PRÁTICA",
    quote: "Coragem também é sentar, pensar e fazer o que precisa ser feito.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 27,
    title: "UM PONTO DE APOIO",
    quote: "Procure primeiro o ponto em que sua vontade ainda pode agir.",
    author: "Marco Aurélio",
  },
  {
    month: 6,
    day: 28,
    title: "O MUNDO NÃO PROMETEU FACILIDADE",
    quote:
      "A dificuldade não é injusta por existir; ela é apenas parte da vida.",
    author: "Sêneca",
  },
  {
    month: 6,
    day: 29,
    title: "SEJA MAIOR QUE A REAÇÃO INICIAL",
    quote: "A primeira reação raramente é a melhor conselheira.",
    author: "Epicteto",
  },
  {
    month: 6,
    day: 30,
    title: "RESOLVER É UMA VIRTUDE",
    quote:
      "Toda vez que você age com clareza diante do problema, fortalece seu caráter.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 1,
    title: "DEVER",
    quote:
      "Faça o que lhe cabe como ser humano, com dignidade e sem hesitação inútil.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 2,
    title: "O DEVER MAIS PRÓXIMO",
    quote:
      "Nem sempre o grande dever está longe; muitas vezes ele está no que está à sua frente agora.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 3,
    title: "SEM TEATRO",
    quote: "Cumprir o dever não exige pose, exige constância.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 4,
    title: "O PAPEL QUE É SEU",
    quote:
      "Você não escolhe tudo no mundo, mas escolhe como representar o papel que lhe coube.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 5,
    title: "RESPONSABILIDADE",
    quote: "Assumir o que é seu sem fugir já é uma forma de força.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 6,
    title: "DEVER NÃO DEPENDE DE HUMOR",
    quote:
      "O que é correto continua sendo correto mesmo quando você não está disposto.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 7,
    title: "SEJA CONFIÁVEL",
    quote:
      "O caráter se revela em quem faz o que deve ser feito quando seria fácil fugir.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 8,
    title: "NÃO ABANDONE O POSTO",
    quote:
      "A dificuldade não cancela o dever; apenas testa sua fidelidade a ele.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 9,
    title: "O DEVER ORGANIZA",
    quote:
      "Muitas confusões desaparecem quando você volta ao que realmente lhe cabe.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 10,
    title: "LEALDADE AO BEM",
    quote: "Permaneça leal ao que é justo, ainda que ninguém esteja olhando.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 11,
    title: "NÃO TERCEIRIZE O QUE É SEU",
    quote: "Há responsabilidades que ninguém pode viver no seu lugar.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 12,
    title: "SERVIR AO TODO",
    quote:
      "Somos feitos para cooperar, como pés, mãos e olhos num mesmo corpo.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 13,
    title: "DISCIPLINA DO PAPEL",
    quote:
      "O que importa não é o tamanho do papel, mas a nobreza com que você o vive.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 14,
    title: "SEM DESCULPAS ELEGANTES",
    quote: "Algumas desculpas soam nobres, mas ainda são fuga.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 15,
    title: "O DEVER DO DIA",
    quote:
      "Não carregue todos os deveres da vida de uma vez; cumpra bem o do dia.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 16,
    title: "FIRMEZA",
    quote:
      "A firmeza cresce quando você faz o que precisa ser feito sem se distrair com o resto.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 17,
    title: "NÃO RECLAME DO QUE É NOBRE",
    quote:
      "Se é digno, não trate como castigo aquilo que ajuda a formar seu caráter.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 18,
    title: "DEVER COM HUMANIDADE",
    quote: "Seja firme no dever, mas sem perder a delicadeza do humano.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 19,
    title: "A VIRTUDE DO COMPROMISSO",
    quote:
      "Comprometer-se com o correto evita que a vida vire improviso permanente.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 20,
    title: "RESPEITE SUA FUNÇÃO",
    quote: "Quando você honra sua função, honra também a ordem da vida.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 21,
    title: "DEVER SEM ASPEREZA",
    quote: "Não use o dever como desculpa para perder a bondade.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 22,
    title: "PERMANEÇA NO CAMINHO",
    quote: "Mesmo cansado, ainda é possível caminhar com retidão.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 23,
    title: "FAÇA O QUE É SEU",
    quote: "Não inveje o caminho dos outros a ponto de abandonar o seu.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 24,
    title: "A RESPONSABILIDADE FORTALECE",
    quote:
      "Quanto mais você assume o que é seu, menos vive à mercê da confusão.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 25,
    title: "DEVER E PAZ",
    quote: "Há paz em cumprir o que é correto mesmo sem recompensa imediata.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 26,
    title: "POSTURA",
    quote: "Seu dever também aparece no modo como você suporta o inevitável.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 27,
    title: "NÃO NEGOCIE O ESSENCIAL",
    quote: "Quando tudo parecer confuso, mantenha intacto o que é essencial.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 28,
    title: "SEJA DIGNO DO DIA",
    quote: "Que o dia termine podendo dizer: fiz o que me cabia com honra.",
    author: "Sêneca",
  },
  {
    month: 7,
    day: 29,
    title: "NÃO FUJA DE SI",
    quote: "Abandonar o dever é, em parte, abandonar a si mesmo.",
    author: "Epicteto",
  },
  {
    month: 7,
    day: 30,
    title: "O BEM COMUM",
    quote:
      "O ser humano floresce mais quando se lembra de que não vive só para si.",
    author: "Marco Aurélio",
  },
  {
    month: 7,
    day: 31,
    title: "FIDELIDADE INTERIOR",
    quote:
      "No fim, o dever é uma forma de fidelidade ao que você sabe que é bom.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 1,
    title: "PRAGMATISMO",
    quote: "Não se perca em teoria quando a vida pede conduta.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 2,
    title: "O ÚTIL E O ESSENCIAL",
    quote: "Nem tudo que ocupa a mente merece virar tarefa.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 3,
    title: "FAÇA O QUE FUNCIONA",
    quote: "A sabedoria prática prefere a clareza ao exibicionismo.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 4,
    title: "MENOS IDEIA, MAIS AJUSTE",
    quote:
      "Em vez de sonhar com o ideal perfeito, melhore o que está diante de você.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 5,
    title: "NÃO COMPLIQUE",
    quote:
      "Grande parte do desgaste vem de insistir em tornar a vida mais confusa do que ela precisa ser.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 6,
    title: "A SABEDORIA É OPERACIONAL",
    quote: "O pensamento só amadurece de verdade quando ajuda a viver melhor.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 7,
    title: "AÇÃO ENXUTA",
    quote: "Eliminar excessos também é uma forma de inteligência.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 8,
    title: "NÃO LUTE COM O DESNECESSÁRIO",
    quote: "Sua energia é valiosa demais para ser entregue ao que não importa.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 9,
    title: "PRÁTICO NÃO É RASO",
    quote:
      "Ser prático não é empobrecer a vida, é dar direção ao que realmente importa.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 10,
    title: "SEJA DIRETO",
    quote: "Quando a verdade é simples, não a esconda atrás de complicações.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 11,
    title: "PROBLEMAS PEDEM AÇÃO CLARA",
    quote:
      "Nem todo problema precisa de uma grande filosofia; alguns precisam de um próximo passo sensato.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 12,
    title: "ECONOMIA INTERIOR",
    quote: "A mente sábia não desperdiça força com o que não produz bem algum.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 13,
    title: "CLAREZA PRÁTICA",
    quote:
      "Veja o que é preciso, faça o que é possível e descarte o que só complica.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 14,
    title: "SEM ENFEITE",
    quote: "A vida melhora quando você troca excessos por sobriedade.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 15,
    title: "FAÇA O BÁSICO BEM FEITO",
    quote: "Muitas vitórias nascem de fazer o simples com constância.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 16,
    title: "PRIORIZE",
    quote:
      "A clareza prática começa quando você para de tratar tudo como igual.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 17,
    title: "NÃO COMPRE TEMPO COM ANSIEDADE",
    quote: "Agitação não acelera a solução; muitas vezes só a embaralha.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 18,
    title: "UTILIDADE",
    quote: "Pergunte menos se parece grandioso e mais se é de fato útil.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 19,
    title: "TRABALHE COM O QUE HÁ",
    quote:
      "A maturidade prática começa quando você trabalha com a realidade disponível.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 20,
    title: "SOLIDEZ",
    quote:
      "O que é sólido quase sempre parece menos glamouroso do que o que é superficial.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 21,
    title: "FOQUE NO RESULTADO CERTO",
    quote: "Não gaste sua vida otimizando o que nem deveria ocupar seu centro.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 22,
    title: "MENOS DISPERSÃO",
    quote:
      "A vida se torna mais governável quando você para de servir a dez direções ao mesmo tempo.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 23,
    title: "PRATICIDADE É LIBERDADE",
    quote: "Quanto menos dependente do excesso, mais livre você se torna.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 24,
    title: "SEJA FUNCIONAL",
    quote:
      "O bem também é aquilo que sustenta a vida de modo limpo e possível.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 25,
    title: "SEM ATRASO DESNECESSÁRIO",
    quote:
      "Protelar o que é simples costuma ser só uma forma elegante de fuga.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 26,
    title: "RESPONDA AO DIA",
    quote:
      "A sabedoria prática responde ao dia como ele é, não como gostaria que fosse.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 27,
    title: "O QUE É MANTENÍVEL",
    quote:
      "Escolha caminhos que possam ser sustentados, não só admirados por um instante.",
    author: "Epicteto",
  },
  {
    month: 8,
    day: 28,
    title: "MENOS FANTASIA, MAIS CONSTRUÇÃO",
    quote: "Construa mais do que imagine.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 29,
    title: "FAÇA O NECESSÁRIO",
    quote:
      "Muitas vezes a vida pede menos genialidade e mais fidelidade ao necessário.",
    author: "Sêneca",
  },
  {
    month: 8,
    day: 30,
    title: "PRAGMATISMO COM DIGNIDADE",
    quote: "Ser prático não exige dureza; exige lucidez e compostura.",
    author: "Marco Aurélio",
  },
  {
    month: 8,
    day: 31,
    title: "A ORDEM AJUDA O ESPÍRITO",
    quote:
      "Uma vida mais simples também abre mais espaço para uma mente melhor.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 1,
    title: "FORÇA E RESILIÊNCIA",
    quote:
      "Aquilo que se opõe ao caminho pode, se bem usado, tornar-se parte dele.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 2,
    title: "AGUENTAR NÃO É SE ENTREGAR",
    quote: "Resistir com dignidade não é passividade; é firmeza orientada.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 3,
    title: "A PROVA REVELA",
    quote:
      "A dificuldade não cria seu caráter do zero; ela revela o que nele já existe.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 4,
    title: "NÃO CHAME DE MAL TUDO QUE DÓI",
    quote: "Nem todo sofrimento é destruição; alguns são treino.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 5,
    title: "SEJA DIFÍCIL DE QUEBRAR",
    quote: "Uma mente bem treinada não se despedaça a cada mudança do mundo.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 6,
    title: "SUPORTE O QUE VIER",
    quote: "Parte da força é aprender a suportar sem se tornar amargo.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 7,
    title: "O PESO TAMBÉM FORTALECE",
    quote:
      "Algumas cargas, carregadas com sabedoria, ampliam a capacidade da alma.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 8,
    title: "NÃO DESISTA POR DESCONFORTO",
    quote: "O desconforto não é ordem de recuo.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 9,
    title: "SEJA MAIOR QUE A MARÉ",
    quote:
      "As circunstâncias mudam; a firmeza interior precisa aprender a permanecer.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 10,
    title: "PERMANEÇA EM PÉ",
    quote:
      "Seu trabalho não é impedir toda tempestade, mas manter o centro durante ela.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 11,
    title: "TREINO DE ALMA",
    quote: "A adversidade pode ser o campo de treino da liberdade interior.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 12,
    title: "RESILIÊNCIA NÃO É RIGIDEZ",
    quote: "O forte não é o que nunca dobra, mas o que não se parte.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 13,
    title: "SUPORTE COM NOBREZA",
    quote: "A dor não precisa roubar sua dignidade.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 14,
    title: "PACIÊNCIA FORTE",
    quote: "Há momentos em que a coragem aparece como paciência perseverante.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 15,
    title: "NÃO SE DEIXE DEFINIR PELO GOLPE",
    quote: "Você é mais que aquilo que sofreu.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 16,
    title: "A PROVA NÃO É O FIM",
    quote: "Uma fase dura é capítulo, não identidade.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 17,
    title: "RESPONDA COM ALTURA",
    quote: "Mesmo ferido, você ainda pode responder com caráter.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 18,
    title: "NÃO ALIMENTE O DESALENTO",
    quote: "A dificuldade basta; não lhe acrescente rendição antecipada.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 19,
    title: "O TEMPO DO TREINO",
    quote: "Algumas virtudes só amadurecem quando a vida aperta.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 20,
    title: "APRENDA A SUPORTAR",
    quote: "Quem aprende a suportar com sabedoria amplia sua liberdade.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 21,
    title: "MANTENHA-SE HUMANO",
    quote: "A dor pode endurecer ou aprofundar; escolha o caminho mais nobre.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 22,
    title: "CONTINUE",
    quote: "Nem todo dia pede brilho; alguns pedem apenas continuidade.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 23,
    title: "RESILIÊNCIA É RITMO",
    quote: "Seguir, mesmo devagar, ainda é uma forma de vencer a queda.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 24,
    title: "SOBRIEDADE NA ADVERSIDADE",
    quote: "Não faça da adversidade um palco; faça dela um professor.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 25,
    title: "SEGURE O QUE IMPORTA",
    quote:
      "Quando tudo balançar, segure o essencial: julgamento, caráter e dever.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 26,
    title: "A FORÇA CERTA",
    quote:
      "A verdadeira força não é esmagar o mundo, mas não ser esmagado por ele.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 27,
    title: "SEJA PACIENTE COM O PROCESSO",
    quote:
      "A cura e o fortalecimento raramente obedecem ao relógio da ansiedade.",
    author: "Sêneca",
  },
  {
    month: 9,
    day: 28,
    title: "NÃO SE RASGUE POR DENTRO",
    quote: "Já basta o peso do mundo; não se torne seu próprio agressor.",
    author: "Marco Aurélio",
  },
  {
    month: 9,
    day: 29,
    title: "A QUEDA NÃO CANCELA A MARCHA",
    quote: "Reerguer-se continua sendo parte do caminho.",
    author: "Epicteto",
  },
  {
    month: 9,
    day: 30,
    title: "PERSEVERANÇA COM DIGNIDADE",
    quote:
      "A resiliência mais bela é a que preserva o caráter enquanto suporta.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 1,
    title: "VIRTUDE E BONDADE",
    quote: "A melhor resposta ao mundo é manter o caráter íntegro.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 2,
    title: "SEJA BOM SEM ALARDE",
    quote: "A bondade não precisa de anúncio para continuar sendo nobre.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 3,
    title: "A VIRTUDE É A PRÁTICA",
    quote: "Não fale demais sobre o bem; pratique-o.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 4,
    title: "BONDOSO E FIRME",
    quote:
      "Ser bom não exige ser fraco; exige ser justo sem dureza desnecessária.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 5,
    title: "CARÁTER ANTES DE IMAGEM",
    quote: "Importa mais ser correto do que parecer admirável.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 6,
    title: "NÃO NEGOCIE O BEM",
    quote:
      "A conveniência do momento não deve governar o que você sabe que é reto.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 7,
    title: "A BONDADE TAMBÉM É DISCIPLINA",
    quote: "Ser gentil de forma consistente é uma força treinada.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 8,
    title: "FAÇA O CERTO MESMO SEM TESTEMUNHAS",
    quote: "A consciência é plateia suficiente para a virtude.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 9,
    title: "SEJA JUSTO PRIMEIRO",
    quote: "A justiça deve preceder a conveniência.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 10,
    title: "A BONDADE É UM DEVER",
    quote: "Fomos feitos para cooperar, ajudar e não ferir inutilmente.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 11,
    title: "NOBREZA SILENCIOSA",
    quote: "A nobreza mais sólida quase sempre é discreta.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 12,
    title: "NÃO DEVOLVA O MAL",
    quote: "Responder ao erro com mais erro apenas amplia o dano.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 13,
    title: "A MEDIDA DO HOMEM",
    quote: "O valor de uma pessoa aparece na forma como trata os outros.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 14,
    title: "SEJA DIFERENTE DO QUE O FERIU",
    quote: "Não permita que a agressão alheia molde seu caráter.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 15,
    title: "BONDOSO NÃO É INGÊNUO",
    quote: "A bondade madura enxerga a realidade e ainda escolhe o bem.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 16,
    title: "AJA DE ACORDO COM A NATUREZA HUMANA",
    quote: "O ser humano floresce mais quando vive com justiça e utilidade.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 17,
    title: "VIRTUDE NÃO É PERFORMANCE",
    quote: "O bem verdadeiro não precisa de encenação.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 18,
    title: "FAÇA O BEM COMO QUEM RESPIRA",
    quote:
      "Que a bondade se torne tão natural quanto o hábito de cuidar do essencial.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 19,
    title: "NÃO SE CORROMPA",
    quote: "É melhor perder alguma vantagem do que perder a si mesmo.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 20,
    title: "SEJA RETO NO PEQUENO",
    quote:
      "A virtude não nasce apenas nos grandes atos, mas na integridade diária.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 21,
    title: "CARÁTER É CONTINUIDADE",
    quote: "Você se torna aquilo que repete em silêncio todos os dias.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 22,
    title: "BONDADE COM LIMITES",
    quote: "Ser bom não é se abandonar; é agir com justiça, inclusive consigo.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 23,
    title: "A VIRTUDE SIMPLIFICA",
    quote: "Quando você sabe o que é certo, muitas confusões perdem força.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 24,
    title: "SEJA ÚTIL",
    quote: "A bondade também se manifesta em ser alguém útil ao todo.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 25,
    title: "A ALMA NÃO SE ENRIQUECE COM O VÍCIO",
    quote:
      "Nada ganho por corrupção compensa a perda interior que isso provoca.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 26,
    title: "NÃO SEJA DURO PARA PARECER FORTE",
    quote: "Dureza sem sabedoria é apenas brutalidade melhor vestida.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 27,
    title: "HUMANIDADE",
    quote:
      "Lembre-se de que todos erram; isso não apaga a justiça, mas qualifica sua resposta.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 28,
    title: "A ESCOLHA NOBRE",
    quote: "Mesmo cercado de exemplos ruins, você ainda pode escolher o bem.",
    author: "Epicteto",
  },
  {
    month: 10,
    day: 29,
    title: "SEJA INTEIRO",
    quote:
      "Virtude é quando pensamento, palavra e ação param de viver em guerra.",
    author: "Sêneca",
  },
  {
    month: 10,
    day: 30,
    title: "O BEM COMO NORTE",
    quote: "Quando o bem vira norte, a vida para de girar em torno do ego.",
    author: "Marco Aurélio",
  },
  {
    month: 10,
    day: 31,
    title: "TERMINE O MÊS EM PAZ",
    quote:
      "Melhor do que impressionar é terminar o dia em paz com a própria consciência.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 1,
    title: "ACEITAÇÃO / AMOR FATI",
    quote: "Não apenas suporte o que vem; aprenda a trabalhar com isso.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 2,
    title: "ACEITAR NÃO É DESISTIR",
    quote: "Aceitar a realidade é o começo da ação lúcida, não o fim dela.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 3,
    title: "NÃO BRIGUE COM O REAL",
    quote:
      "Lutar contra o que já aconteceu só multiplica o peso do acontecimento.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 4,
    title: "AMOR AO DESTINO",
    quote:
      "Receba o que veio como matéria para virtude, não como sentença de derrota.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 5,
    title: "O QUE É, É",
    quote:
      "A serenidade cresce quando você para de exigir que o passado seja diferente.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 6,
    title: "NÃO ACRESCENTE RESISTÊNCIA",
    quote:
      "Parte da dor vem do fato; outra parte vem da recusa em admitir o fato.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 7,
    title: "TRABALHE COM O QUE VEIO",
    quote: "O destino não pede aprovação; pede resposta.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 8,
    title: "ACEITE O QUE FOGE AO CONTROLE",
    quote:
      "A liberdade não está em mandar em tudo, mas em responder bem ao que vem.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 9,
    title: "MENOS REVOLTA, MAIS PRESENÇA",
    quote:
      "A revolta prolongada escurece aquilo que a presença poderia esclarecer.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 10,
    title: "COOPERE COM A VIDA",
    quote:
      "Quanto antes você cooperar com a realidade, antes recupera sua força de agir.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 11,
    title: "O FATUM NÃO É INIMIGO",
    quote: "Nem tudo que você não escolheu veio para destruí-lo.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 12,
    title: "NÃO PEÇA OUTRO UNIVERSO",
    quote: "A maturidade começa quando você para de pedir um mundo impossível.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 13,
    title: "AMOR FATI NA PRÁTICA",
    quote:
      "Dizer sim ao que veio não é gostar de tudo, é parar de ser rasgado por dentro.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 14,
    title: "RECEBA E ORIENTE",
    quote:
      "Você não governa todos os acontecimentos, mas governa o uso que fará deles.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 15,
    title: "SEM GUERRA INTERIOR DESNECESSÁRIA",
    quote:
      "Aceitar o inevitável poupa a alma de uma guerra que ela nunca venceria.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 16,
    title: "CONVERTER O PESO",
    quote:
      "Mesmo o que pesa pode ser convertido em disciplina, lucidez e caráter.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 17,
    title: "NÃO ATRASE O ENCONTRO COM O REAL",
    quote: "Quanto mais você adia aceitar, mais prolonga a desordem.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 18,
    title: "A REALIDADE NÃO PEDE LICENÇA",
    quote: "Ela chega como chega; o que muda tudo é como você a recebe.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 19,
    title: "SEJA FLEXÍVEL SEM SE PERDER",
    quote:
      "Aceitar não significa dissolver seu caráter, mas adaptá-lo com sabedoria.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 20,
    title: "DEIXE O PASSADO PARAR DE GOVERNAR",
    quote:
      "O fato já passou; não permita que ele continue escolhendo por você hoje.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 21,
    title: "PAZ COM O QUE NÃO VOLTA",
    quote:
      "A paz chega mais perto quando você para de negociar com o irreversível.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 22,
    title: "NÃO CHAME DE CASTIGO TUDO QUE FRUSTRA",
    quote:
      "Nem toda frustração é punição; às vezes é apenas o mundo seguindo seu curso.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 23,
    title: "A FORÇA DE ADMITIR",
    quote:
      "Admitir o que é verdadeiro exige mais força do que insistir na negação.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 24,
    title: "MENOS 'POR QUE EU?', MAIS 'E AGORA?'",
    quote:
      "A vida melhora quando você troca o lamento pela resposta responsável.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 25,
    title: "RECEBA O DIA COMO ELE VEIO",
    quote:
      "Nem todo dia virá no formato desejado, mas ainda pode ser vivido com nobreza.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 26,
    title: "ACEITAÇÃO É CLAREZA",
    quote: "Ver o real como real é uma forma de sabedoria prática.",
    author: "Epicteto",
  },
  {
    month: 11,
    day: 27,
    title: "NÃO PROLONGUE A RESISTÊNCIA",
    quote:
      "Quanto mais cedo você aceitar o inevitável, mais cedo volta a agir.",
    author: "Sêneca",
  },
  {
    month: 11,
    day: 28,
    title: "COLOQUE O DESTINO A SEU FAVOR",
    quote:
      "Você não escolhe tudo que acontece, mas pode escolher o tipo de pessoa que isso formará.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 29,
    title: "AMOR FATI",
    quote:
      "Não queira só tolerar o que veio; tente aprender a dizer sim a ele.",
    author: "Marco Aurélio",
  },
  {
    month: 11,
    day: 30,
    title: "TERMINE O MÊS EM ACORDO COM O REAL",
    quote:
      "A serenidade amadurece quando a alma deixa de exigir que o mundo se curve a ela.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 1,
    title: "MEDITAÇÃO SOBRE A MORTALIDADE",
    quote: "Lembrar que a vida é finita devolve peso ao que realmente importa.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 2,
    title: "O TEMPO É LIMITADO",
    quote: "Não viva como se houvesse sempre depois.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 3,
    title: "A MORTE DÁ MEDIDA À VIDA",
    quote: "Quem se lembra do fim costuma viver o presente com mais verdade.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 4,
    title: "NÃO DESPERDICE O DIA",
    quote: "Cada dia perdido é uma parte da vida entregue sem retorno.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 5,
    title: "VIVER AGORA",
    quote: "A morte não pede morbidez, pede presença.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 6,
    title: "O FIM TORNA O ESSENCIAL MAIS CLARO",
    quote:
      "Quando o tempo deixa de parecer infinito, o supérfluo perde prestígio.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 7,
    title: "ACEITE A CONDIÇÃO HUMANA",
    quote: "Morrer não é um acidente da vida; é parte dela.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 8,
    title: "NÃO ADIE A VIDA BOA",
    quote: "A vida boa não deve ser um projeto sempre adiado.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 9,
    title: "A PRESSA CERTA",
    quote: "Não se apresse em tudo; apresse-se apenas em viver com verdade.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 10,
    title: "MEMENTO MORI",
    quote:
      "Lembrar da morte é uma forma de proteger a vida contra a distração.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 11,
    title: "O DIA PODE SER O ÚLTIMO",
    quote:
      "Viva este dia de um modo que não precise pedir desculpas à própria consciência.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 12,
    title: "NÃO SE AGARRE AO INÚTIL",
    quote: "Muito do que prendemos não nos acompanhará até o fim.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 13,
    title: "O FIM ENSINA SOBRIEDADE",
    quote: "A consciência da morte torna o ego menos barulhento.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 14,
    title: "SEJA ENCONTRADO VIVENDO",
    quote: "Quando o fim vier, que o encontre vivendo de forma digna.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 15,
    title: "VIDA CURTA, ESCOLHAS IMPORTANTES",
    quote: "A brevidade da vida exige prioridades, não pânico.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 16,
    title: "MORTALIDADE E GENTILEZA",
    quote:
      "Lembrar que todos somos mortais torna mais fácil abandonar a arrogância.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 17,
    title: "NÃO VIVA EM ENSAIO",
    quote: "A vida real não começa depois de você se sentir pronto.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 18,
    title: "O TEMPO COMO TESOURO",
    quote:
      "Tempo não é algo que se encontra; é algo que se guarda ou se perde.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 19,
    title: "MORTALIDADE E JUSTIÇA",
    quote:
      "Ser mortal deveria torná-lo mais justo, não mais apressado para o ego.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 20,
    title: "A VIDA PEDE CONCLUSÃO",
    quote: "A finitude não é crueldade; é o que dá forma à vida humana.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 21,
    title: "NÃO POSSE, MAS USO",
    quote:
      "Você não possui a vida como objeto; você a usa enquanto ela lhe é dada.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 22,
    title: "SEJA DIGNO DO TEMPO RECEBIDO",
    quote: "A pergunta não é quanto tempo houve, mas o que foi feito dele.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 23,
    title: "MORRER SEM TER VIVIDO",
    quote: "Pior que morrer cedo é viver sem jamais começar de verdade.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 24,
    title: "O FIM APROXIMA O ESSENCIAL",
    quote:
      "Quando o fim é lembrado, o amor, o dever e a verdade se tornam mais claros.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 25,
    title: "GRATIDÃO PELO DIA",
    quote:
      "Receba o dia como um empréstimo precioso, não como direito garantido.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 26,
    title: "NÃO TEMA TANTO O FIM",
    quote: "Tema mais desperdiçar a vida do que perdê-la um dia.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 27,
    title: "UM DIA BEM VIVIDO",
    quote:
      "Uma vida digna se constrói em dias bem vividos, não em promessas distantes.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 28,
    title: "O FIM COMO CONSELHEIRO",
    quote:
      "Deixe a mortalidade aconselhar suas escolhas, não paralisar seu espírito.",
    author: "Epicteto",
  },
  {
    month: 12,
    day: 29,
    title: "SIMPLES E VERDADEIRO",
    quote: "No fim, importa menos o brilho e mais a verdade com que se viveu.",
    author: "Sêneca",
  },
  {
    month: 12,
    day: 30,
    title: "PREPARE-SE VIVENDO BEM",
    quote: "A melhor preparação para o fim é viver hoje com consciência limpa.",
    author: "Marco Aurélio",
  },
  {
    month: 12,
    day: 31,
    title: "TERMINE O ANO DESPERTO",
    quote:
      "Que o fim do ano o encontre mais desperto para o valor do tempo e da vida.",
    author: "Marco Aurélio",
  },
];

export function getStoicQuoteByDate(dateKey: string): DailyStoicQuote | null {
  const [, month, day] = dateKey.split("-").map(Number);

  const found = STOIC_QUOTES.find(
    (item) => item.month === month && item.day === day,
  );

  return found || null;
}
